# Generated by Django 4.1.5 on 2023-05-04 15:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wonderhub.models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0003_alter_course_instructor_alter_instructor_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=wonderhub.models.Lesson.folder_name),
        ),
        migrations.AddField(
            model_name='lesson',
            name='note',
            field=models.FileField(blank=True, null=True, upload_to=wonderhub.models.Lesson.folder_name),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=wonderhub.models.Lesson.folder_name),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wonderhub.instructor'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wonderhub.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wonderhub.student')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='wonderhub.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(to='wonderhub.category'),
        ),
    ]
