# Generated by Django 4.1.5 on 2023-05-06 07:56

from django.db import migrations, models
import wonderhub.models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0004_lesson_audio_lesson_note_lesson_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=300, upload_to=wonderhub.models.Course.folder_name, width_field=360),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='wonderhub.student'),
        ),
    ]
