# Generated by Django 4.1.5 on 2023-05-11 12:28

from django.db import migrations, models
import wonderhub.models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0005_course_image_alter_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=wonderhub.models.Course.folder_name),
        ),
    ]
