# Generated by Django 4.1.5 on 2023-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0006_category_is_top_course_is_top_instructor_is_top_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='profile.svg', upload_to='instructor'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
