# Generated by Django 4.1.5 on 2023-07-21 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0007_instructor_about_instructor_image_instructor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='previews'),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(default='this is my opinion'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='profile.svg', upload_to='student'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='wonderhub.course'),
        ),
    ]
