# Generated by Django 4.1.5 on 2023-09-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0011_alter_comment_created_at_alter_course_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='wonderhub.instructor'),
        ),
    ]
