# Generated by Django 4.1.5 on 2023-09-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0012_course_approved_course_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='payable',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
