# Generated by Django 4.1.5 on 2023-09-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0015_alter_bankaccount_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
