# Generated by Django 4.1.5 on 2023-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0016_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
