# Generated by Django 4.1.5 on 2023-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0018_answerchoice_userchoice_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='question',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='userchoice',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='selected_answer',
            field=models.ManyToManyField(to='wonderhub.answerchoice'),
        ),
    ]
