# Generated by Django 4.1.5 on 2023-10-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0019_remove_userchoice_question_userchoice_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='wonderhub.course'),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('s', 'success'), ('p', 'pending'), ('f', 'failed')], max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('Instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wonderhub.instructor')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
        ),
    ]
