# Generated by Django 4.1.5 on 2023-10-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0020_instructor_balance_alter_quiz_course_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='Instructor',
            new_name='instructor',
        ),
    ]
