# Generated by Django 5.1 on 2024-12-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderhub', '0023_lesson_lesson_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='WYWL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_you_will_learn', to='wonderhub.course')),
            ],
        ),
    ]
