# Generated by Django 4.1.5 on 2023-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
