# Generated by Django 4.1.5 on 2023-02-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_embed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
