# Generated by Django 4.1.5 on 2023-04-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                #('author', models.CharField(blank=True, max_length=50, null=True)),
                #('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='comics')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                #('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('comic_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.ManyToManyField(to='nimic.category')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                #('tag', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='comics')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                #('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('episode_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='nimic.comic')),
            ],
        ),
#        migrations.CreateModel(
#            name='Profile',
#            fields=[
#                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                ('image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
#                ('is_subscribed', models.BooleanField(default=False)),
#                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
#            ],
#        ),
    ]
