# Generated by Django 4.1.5 on 2023-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
