# Generated by Django 4.1.5 on 2023-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nimic', '0002_comic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
