# Generated by Django 4.1.5 on 2023-04-18 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nimic', '0003_comic_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
