# Generated by Django 4.1.5 on 2023-04-18 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nimic', '0004_comic_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
