# Generated by Django 3.2.13 on 2010-01-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_cartitem_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
